version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - appnet

  consumer:
    build:
      context: ./Alert.Consumer
    container_name: alert-consumer
    depends_on:
      - rabbitmq
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
